### YamlMime:ManagedReference
items:
- uid: VEDriversLite.Security
  commentId: N:VEDriversLite.Security
  id: VEDriversLite.Security
  children:
  - VEDriversLite.Security.ECDSAProvider
  - VEDriversLite.Security.EncryptionKey
  - VEDriversLite.Security.SecurityUtils
  - VEDriversLite.Security.SymetricProvider
  langs:
  - csharp
  - vb
  name: VEDriversLite.Security
  nameWithType: VEDriversLite.Security
  fullName: VEDriversLite.Security
  type: Namespace
  assemblies:
  - VEDriversLite
references:
- uid: VEDriversLite.Security.ECDSAProvider
  commentId: T:VEDriversLite.Security.ECDSAProvider
  name: ECDSAProvider
  nameWithType: ECDSAProvider
  fullName: VEDriversLite.Security.ECDSAProvider
- uid: VEDriversLite.Security.EncryptionKey
  commentId: T:VEDriversLite.Security.EncryptionKey
  parent: VEDriversLite.Security
  name: EncryptionKey
  nameWithType: EncryptionKey
  fullName: VEDriversLite.Security.EncryptionKey
- uid: VEDriversLite.Security.SecurityUtils
  commentId: T:VEDriversLite.Security.SecurityUtils
  name: SecurityUtils
  nameWithType: SecurityUtils
  fullName: VEDriversLite.Security.SecurityUtils
- uid: VEDriversLite.Security.SymetricProvider
  commentId: T:VEDriversLite.Security.SymetricProvider
  name: SymetricProvider
  nameWithType: SymetricProvider
  fullName: VEDriversLite.Security.SymetricProvider
- uid: VEDriversLite.Security
  commentId: N:VEDriversLite.Security
  name: VEDriversLite.Security
  nameWithType: VEDriversLite.Security
  fullName: VEDriversLite.Security
